# Generated by Django 2.1.7 on 2019-04-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllBor',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('nomor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('id_bor', models.CharField(blank=True, max_length=254, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('z', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('depth_from', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('depth_bott', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('lithologi', models.CharField(blank=True, max_length=254, null=True)),
                ('azimuth', models.CharField(blank=True, max_length=254, null=True)),
                ('inklinasi', models.CharField(blank=True, max_length=254, null=True)),
                ('seam', models.CharField(blank=True, max_length=254, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_bor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WwmReklamasi',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('luasan', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('kemiringan', models.IntegerField(blank=True, null=True)),
                ('tinggi', models.IntegerField(blank=True, null=True)),
                ('lebar', models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True)),
                ('panjang', models.IntegerField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wwm_reklamasi',
                'managed': False,
            },
        ),
    ]
